### ISSUE TITLE
Varya: Consider removing duplicate post meta on single post page. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#27]
We currently have two lines of Meta content for each post on single post pages. When there isn't much content (or when there's no post title) this looks weird. @allancole: are there any potential downsides to us just removing the top one? 

It looks like we have separate (identical?) functions for each of those: [`varya_entry_meta()`](https://github.com/Automattic/themes-workspace/blob/daf833b07ace29008e0b2b8cfae0382cd694a628/varya/inc/template-tags.php#L70-L133) and [`varya_entry_footer()`](https://github.com/Automattic/themes-workspace/blob/daf833b07ace29008e0b2b8cfae0382cd694a628/varya/inc/template-tags.php#L135-L198). Maybe we can just delete the first one? 

---

Current: 

![Screen Shot 2020-03-30 at 1 02 23 PM](https://user-images.githubusercontent.com/1202812/77940493-c258b900-7286-11ea-9a56-e62d4d86ffe8.png)

Recommended: 

![Screen Shot 2020-03-30 at 1 02 09 PM](https://user-images.githubusercontent.com/1202812/77940508-c97fc700-7286-11ea-9d31-06b34dfbe3cd.png)

**Comment by allancole** [comment]
> are there any potential downsides to us just removing the top one?

No downsides really. They are both there intentionally, but how its implemented is definitely worth an audit. Since there isn’t a Block for post meta (yet), I wanted there to be an easy way for child themes to do whatever they want here. Some child themes may want the meta above the content and others below, others may want author credits above, and only comment links below. 

Right now, child themes can achieve that be adding their own `varya_entry_meta()` or `varya_entry_footer()` functions in `themes/child-theme-name/functions.php` which will allow them to replace whats in the parent with any function in a non-destructive way. 

If we take out just the top one (without a function or an action to hook in to), then it means child themes will need to override all the `content-???.php` templates in the parent entirely, creating more complexity in the child theme than I think its worth. 

It’d probably be better to empty the top function and replace it with an action so child themes can easily put stuff there if they want to, but still have it empty by default for Varya.

**Comment by kjellr** [comment]
Fixed in #30
