### ISSUE TITLE
Varya: Gutenberg's line height control does not work in the editor. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#37]
Same issue as reported over in https://github.com/Automattic/themes/issues/1895

Gutenberg 7.9 introduces a `--wp--typography--line-height` CSS variable when the user adjusts the line height in the sidebar. The specificity of Varya's CSS overrides this new rule, preventing it from kicking into effect.

<img width="912" alt="Screen Shot 2020-04-01 at 11 17 35 AM" src="https://user-images.githubusercontent.com/1202812/78154803-aed65b00-740a-11ea-85d7-5e887e3383d4.png">

In general, how should we handle these new WP-provided variables? Should we just start migrating the names of the Varya variables each time one of these new ones becomes available?

**Comment by allancole** [comment]
> Should we just start migrating the names of the Varya variables each time one of these new ones becomes available?

Yup, that would be ideal. Gonna do some testing in a PR for this but should be pretty straight forward to add this kind of support.

**Comment by allancole** [comment]
I did some digging on this its a little tough to follow how it’s intended to work. 

There appears to only be one variable `--wp--typography--line-height` and its doubly used for both paragraphs and headings in kind of an awkward way. The variable is applied to headings , inline in the editor and via :root variables on the frontend. Paragraphs work different and only use root variables on both the editor and frontend. This make it tricky to connect the line-heights that exist in the Varya system since we’re using 2 separate variables for headings and paragraphs. 

It also feels like the new line-height option is a block-specific setting (meaning not global), but its actually global. I assumed these settings were block-specific, which would have been much easier to adapt to the Varya system. 

There’s a few different ways to approach adding this support: 

1) Refactor the line-height system to work the same way it does in core (using a single line-height variable). 
2) Strip out the Varya line-heights variables and rely solely on the ones that come from core. If we do this, we’d need a way to set default line-heights for the editor and the front end—not sure if thats possible yet. 
3) We can push for separating the heading and line-height css-variables in Gutenberg so that they’re easier to understand and override from themes in general. We could also suggest a non-inline style method for headings which would make this all easier to understand as well.

**Comment by jffng** [comment]
Thanks for digging and laying that out @allancole! My early thoughts: 

> 1. Refactor the line-height system to work the same way it does in core (using a single line-height variable).

we could refactor so that either:
 
a) `--wp--typography--line-height` is only used on the paragraph block, and we override it for everything else using Varya. This could make sense because (from what I can tell) the line height UI is only exposed on the paragraph block. 

or 

b) tie `--global--line-height-body` to `--wp-typography--line-height`. I don't like this approach because I could see us refactoring every time a small change is made to how the line-height and variables work in core, and this seems to be heavily in flux.


>2. Strip out the Varya line-heights variables and rely solely on the ones that come from core. 

This doesn't seem like a good solution because it doesn't give us adequate design control right now. Also since "we’d need a way to set default line-heights for the editor and the front end—not sure if thats possible yet."

I think this is only possible via an `experimental-theme.json` in the theme and FSE experiment enabled.

> 3. We can push for separating the heading and line-height css-variables in Gutenberg so that they’re easier to understand and override from themes in general. We could also suggest a non-inline style method for headings which would make this all easier to understand as well.

I also think this is important: we need to advocate for more sensible design control via the right CSS variables. But that evolution is going to take way longer than our expectations for shipping this theme.

**Comment by jffng** [comment]
Related Gutenberg PRs:

- Adding line-height controls + related discussion: https://github.com/WordPress/gutenberg/pull/20775
- Enabling global styles without theme support / FSE experiment enabled: https://github.com/WordPress/gutenberg/pull/21346

**Comment by jffng** [comment]
Solved by #44
